server:
  port: 8080

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1/
          predicates:
            - Path=/user/**
        - id: service2
          uri: lb://service2/
          predicates:
            - Path=/contact/**
